# Generated by Django 5.2.3 on 2025-06-28 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille (cm)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True, verbose_name='Tension artérielle systolique')),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True, verbose_name='Tension artérielle diastolique')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque (bpm)')),
                ('symptoms', models.TextField(blank=True, verbose_name='Symptômes')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnostic')),
                ('treatment', models.TextField(blank=True, verbose_name='Traitement prescrit')),
                ('notes', models.TextField(blank=True, verbose_name='Notes additionnelles')),
                ('consultation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='gestion.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='gestion.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='gestion.consultation'),
        ),
    ]
